apiVersion: v1
kind: Pod
metadata:
  namespace: advertisement
  labels:
    app: sleep
    applicationId: "application_2019_01_22_00001"
    queue: "root.advertisement"
  name: task0
spec:
  schedulerName: yunikorn
  containers:
    - name: sleep-5s
      image: "alpine:latest"
      command: ["/bin/ash", "-ec", "while :; do echo '.'; sleep 5 ; done"]
      resources:
        requests:
          cpu: "50m"
          memory: "800M"
        limits:
          cpu: "100m"
          memory: "1000M"
